### ISSUE TITLE
Terminal window opened by Ctrl + Shift + N will not close with "exit"

### ISSUE THREAD

**Issue by 71GA** [DanteAlighierin/foot#2]
I set my `foot` terminal acording to the official guide ([link](https://codeberg.org/dnkl/foot/wiki#how-to-configure-my-shell-to-emit-the-osc-7-escape-sequence)). In other words I made shure shell emits _"OSC 7"_ escape sequence.

Now I can use <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>N</kbd> to open a new `foot` terminal. But when I try to close this newly opened terminal by executing `exit` it will not close! It only echoes `exit` back at me and freezes.

Foot version is 1.6.4-1

**Comment by DanteAlighierin** [comment]
Check updated version
