### ISSUE TITLE
Inner border

### ISSUE THREAD

**Issue by Sbatushe** [DanteAlighierin/foot#3]
Hello, it's possible to add inner border support? This is just a padding added in the terminal area (not window border), which can be horizontal or vertical. Thanks in advance

**Comment by DanteAlighierin** [comment]
> Hello, it's possible to add inner border support? This is just a padding added in the terminal area (not window border), which can be horizontal or vertical. Thanks in advance

All questions to main developer(https://codeberg.org/dnkl)
