### ISSUE TITLE
Ignores the primary screen on Gnome

### ISSUE THREAD

**Issue by arodier** [DanteAlighierin/foot#4]
When using Gnome, I have a laptop and a big screen. The big screen is set as a primary display, and the laptop screen is set as a secondary screen.

All my Gnome applications are starting on the primary script, as you'd expect, but foot starts on the laptop screen every time.

If I move it to the primary screen, when gnome screen saver starts, the terminal is again moved to the laptop screen. This is actually so annoying that I gave up using foot.

**Comment by DanteAlighierin** [comment]
Gm. I'll update mirror to a new actuall version of foot

> When using Gnome, I have a laptop and a big screen. The big screen is set as a primary display, and the laptop screen is set as a secondary screen.
> 
> All my Gnome applications are starting on the primary script, as you'd expect, but foot starts on the laptop screen every time.
> 
> If I move it to the primary screen, when gnome screen saver starts, the terminal is again moved to the laptop screen. This is actually so annoying that I gave up using foot.

**Comment by arodier** [comment]
Thanks, @DanteAlighierin !
