### ISSUE TITLE
--hold flag breaks foot

### ISSUE THREAD

**Issue by jvc84** [DanteAlighierin/foot#5]
If  terminal starts with flag like this: ```foot --hold htop``` and then you exit htop, foot freezes in this state:

![foot_freezes](https://github.com/DanteAlighierin/foot/assets/72560784/0a22fca7-216b-46e3-a6ef-2d0c484fb216)

My temporary solution:

Create file ```~/.config/foot/hold.sh```:

```
#!/bin/bash
${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9} ${10} && bash
```

```sudo chmod +x ~/.config/foot/hold.sh```

Then use ```~/.config/foot/hold.sh``` instead of ```--hold```:

```foot ~/.config/foot/hold.sh htop```

**Comment by DanteAlighierin** [comment]
Will be resolved soon
